service: time-management-frontend
provider:
  name: aws
  stage: dev
  profile: se-demo
  region: eu-west-2
custom:
  client:
    bucketName: time-management-frontend-${opt:stage, self:provider.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
    uploadOrder:
      - .*/apps/.*
      - .*/assets/.*
      - .*/css/.*
      - .*/fonts/.*
      - .*/iconfont/.*
      - .*/images/.*
      - .*/maintmode/.*
      - .*/p2pmigration/.*
      - .*/predictive-engagement-website/.*
      - .*/static/.*
      - .*/testdrive/.*
      - .*/webChatComponent/.*
      - .*/wizard/.*
      - .js
      - .json
      - .ico
      - .txt
      - .html
plugins:
  - serverless-finch
